--
-- PostgreSQL database dump
--

-- Dumped from database version 15.2
-- Dumped by pg_dump version 15.2

-- Started on 2023-03-08 14:17:13

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

DROP DATABASE first_db;
--
-- TOC entry 3337 (class 1262 OID 16398)
-- Name: first_db; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE first_db WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'Ukrainian_Ukraine.1251';


ALTER DATABASE first_db OWNER TO postgres;

\connect first_db

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 217 (class 1259 OID 16618)
-- Name: item; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.item (
    id integer NOT NULL,
    person_id integer,
    item_name character varying(100) NOT NULL
);


ALTER TABLE public.item OWNER TO postgres;

--
-- TOC entry 216 (class 1259 OID 16617)
-- Name: item_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.item ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 214 (class 1259 OID 16475)
-- Name: person; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.person (
    id integer NOT NULL,
    name character varying NOT NULL,
    age integer NOT NULL,
    email character varying NOT NULL,
    date_of_birth date,
    created_at timestamp without time zone,
    mood character varying,
    CONSTRAINT person_age_check CHECK ((age > 0))
);


ALTER TABLE public.person OWNER TO postgres;

--
-- TOC entry 215 (class 1259 OID 16481)
-- Name: person_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.person ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.person_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3331 (class 0 OID 16618)
-- Dependencies: 217
-- Data for Name: item; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.item (id, person_id, item_name) VALUES (2, 9, 'Airpods');
INSERT INTO public.item (id, person_id, item_name) VALUES (3, 9, 'Playstation');
INSERT INTO public.item (id, person_id, item_name) VALUES (4, 9, 'TV');


--
-- TOC entry 3328 (class 0 OID 16475)
-- Dependencies: 214
-- Data for Name: person; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.person (id, name, age, email, date_of_birth, created_at, mood) VALUES (6, 'Bobbby', 23, 'bobby@email.com', NULL, NULL, NULL);
INSERT INTO public.person (id, name, age, email, date_of_birth, created_at, mood) VALUES (9, 'Marley', 34, 'marley@gmial.com', NULL, NULL, NULL);
INSERT INTO public.person (id, name, age, email, date_of_birth, created_at, mood) VALUES (10, 'Tom', 25, 'tom@gmail.com', NULL, NULL, NULL);
INSERT INTO public.person (id, name, age, email, date_of_birth, created_at, mood) VALUES (11, 'Bob', 31, 'bob1@gmail.com', NULL, NULL, NULL);
INSERT INTO public.person (id, name, age, email, date_of_birth, created_at, mood) VALUES (12, 'Bob', 53, 'bob2@gmail.com', NULL, NULL, NULL);
INSERT INTO public.person (id, name, age, email, date_of_birth, created_at, mood) VALUES (13, 'Bob', 28, 'bob3@gmail.com', NULL, NULL, NULL);
INSERT INTO public.person (id, name, age, email, date_of_birth, created_at, mood) VALUES (14, 'Katty', 14, 'katty@gmail.com', NULL, NULL, NULL);
INSERT INTO public.person (id, name, age, email, date_of_birth, created_at, mood) VALUES (15, 'Tommmy', 20, 'tommmy@email.com', '2023-03-08', '2023-03-08 13:46:33.426', NULL);
INSERT INTO public.person (id, name, age, email, date_of_birth, created_at, mood) VALUES (17, 'Marleyi', 20, 'marleyi@gmial.com', '2023-03-08', '2023-03-08 14:14:32.881', 'CALM');


--
-- TOC entry 3338 (class 0 OID 0)
-- Dependencies: 216
-- Name: item_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.item_id_seq', 4, true);


--
-- TOC entry 3339 (class 0 OID 0)
-- Dependencies: 215
-- Name: person_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.person_id_seq', 17, true);


--
-- TOC entry 3184 (class 2606 OID 16622)
-- Name: item item_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.item
    ADD CONSTRAINT item_pkey PRIMARY KEY (id);


--
-- TOC entry 3180 (class 2606 OID 16483)
-- Name: person person_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.person
    ADD CONSTRAINT person_email_key UNIQUE (email);


--
-- TOC entry 3182 (class 2606 OID 16485)
-- Name: person person_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.person
    ADD CONSTRAINT person_pkey PRIMARY KEY (id);


--
-- TOC entry 3185 (class 2606 OID 16623)
-- Name: item item_person_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.item
    ADD CONSTRAINT item_person_id_fkey FOREIGN KEY (person_id) REFERENCES public.person(id) ON DELETE SET NULL;


-- Completed on 2023-03-08 14:17:13

--
-- PostgreSQL database dump complete
--

